language: node_js
env:
  global:
    - CC_TEST_REPORTER_ID=9ccebe1836351143aed5f743676c19b885cd2a7407e46e878bb16ca121b38bbb
matrix:
  include:
    - node_js: 12
  branches:
cache:
  directories: [node_modules]
install: npm install -g npm@latest
after_success: npm run coverage
