language: node_js
env:
  global:
    - CC_TEST_REPORTER_ID=9ccebe1836351143aed5f743676c19b885cd2a7407e46e878bb16ca121b38bbb
matrix:
  include:
    - node_js: 12
  branches:
cache:
  directories: [node_modules]
install: npm ci
after_success: npm run coverage
before_script:
  - psql -c 'create database testdb;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
before_install:
  - sudo cp /etc/postgresql/{9.6,10}/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
deploy:
  provider: heroku
  api_key:
    secure: "5c3d0f110d9d7d3793792417f3d817d3de665343"
  app:
    master: expresspostgre
